services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
      - 8920:8920 # Optional HTTPS port
      - 1900:1900/udp # Service Discovery
      - 7359:7359/udp # Client Discovery
    volumes:
      - /mnt/data/config:/config
      - /mnt/data/cache:/cache
      - /mnt/data/VIdeo:/Movies:ro
      - /mnt/storage/tvshows:/Shows:ro # ':ro' for read-only safety
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.bradleyrogers.online

