services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - JELLYFIN_PublishedServerUrl=http://jellyfin.bradleyrogers.online
    volumes:
      - /mnt/storage/config:/config
      - /mnt/storage/cache:/cache
      - /mnt/sdc_drive/tvshows:/shows
      - /mnt/data/VIdeo:/movies
      
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
    networks:
      - media-network

networks:
  media-network:
    driver: bridge
